testimonials = [
    {'name': 'Bharti',
     'rating': 5,
     'review': 'Good beer, excellent service very fast and helpful',
     'imageUrl': 'assets/Profile/profile1.png',
     },
    {'name': 'Gurpreet Singh',
     'rating': 3,
     'review': "It's one of the best place to hangout in Jalandhar. If you are visiting in night time the open rooftop is best",
     'imageUrl': 'assets/Profile/profile2.png',
     },
    {'name': 'Amrit',
     'rating': 5,
     'review': 'It was a good experience as it was my first visit at BiG Shot, a good stafff',
     'imageUrl': 'assets/Profile/profile3.png',
     },
    {'name': 'Anmol',
     'rating': 3,
     'review': 'Good branded beer,Quick services and helpful Staff, Nice  ambience, Amble parking place, Good Service.',
     'imageUrl': 'assets/Profile/profile4.png',
     },
    {'name': 'Manpreet',
     'rating': 4,
     'review': 'Here the ambiance is nice,super quick services and great taste of beer.',
     'imageUrl': 'assets/Profile/profile5.png',
     }
]


beers = [
    {'brand': 'Bira91',
     'beer': 'Blonde ',
     'alcohol': 4.0,
     'price': 225,
     'quantity': 650,
     'imageUrl': 'assets/Beers/bira-blonde.png'
     },
    {'brand': 'Bira91',
     'beer': 'White Beer',
     'alcohol': 4.9,
     'price': 245,
     'quantity': 650,
     'imageUrl': 'assets/Beers/bira-white.png'
     },
    {'brand': 'Budweiser',
     'beer': 'Magnum',
     'alcohol': 6.5,
     'price': 275,
     'quantity': 650,
     'imageUrl': 'assets/Beers/budwiser-magnum.png'
     },
    {'brand': 'Budweiser',
     'beer': 'Premium',
     'alcohol': 5.0,
     'price': 230,
     'quantity': 650,
     'imageUrl': 'assets/Beers/budwiser-premium.png'
     },
    {'brand': 'Carlsbergs',
     'beer': 'Elephant strong',
     'alcohol': 7.0,
     'price': 195,
     'quantity': 650,
     'imageUrl': 'assets/Beers/carlsberg-elephant.png'
     },
    {'brand': 'Corona',
     'beer': 'Extra',
     'alcohol': 4.6,
     'price': 280,
     'quantity': 650,
     'imageUrl': 'assets/Beers/corona-extra.png'
     },
    {'brand': 'Fosters',
     'beer': 'Strong Premium',
     'alcohol': 7.0,
     'price': 120,
     'quantity': 650,
     'imageUrl': 'assets/Beers/foster-strong.png'
     },
    {'brand': 'Fullers',
     'beer': 'London pride',
     'alcohol': 4.7,
     'price': 290,
     'quantity': 330,
     'imageUrl': 'assets/Beers/fullers-london-pride.png'
     },
    {'brand': 'Godfather',
     'beer': 'Legendary',
     'alcohol': 6.5,
     'price': 180,
     'quantity': 650,
     'imageUrl': 'assets/Beers/godfather-legendary.png'
     },
    {'brand': 'Heineken',
     'beer': 'Large',
     'alcohol': 5.0,
     'price': 200,
     'quantity': 650,
     'imageUrl': 'assets/Beers/heineken-large.png'
     },
    {'brand': 'Kingfisher',
     'beer': 'Premium',
     'alcohol': 4.8,
     'price': 140,
     'quantity': 650,
     'imageUrl': 'assets/Beers/kingfisher-premium.png'
     },
    {'brand': 'Kingfisher',
     'beer': 'Strong',
     'alcohol': 8.0,
     'price': 145,
     'quantity': 650,
     'imageUrl': 'assets/Beers/kingfisher-strong.png'
     },
    {'brand': 'Leffe',
     'beer': 'Bruine',
     'alcohol': 6.5,
     'price': 260,
     'quantity': 330,
     'imageUrl': 'assets/Beers/leffe-bruine.png'
     },
    {'brand': 'Leffe',
     'beer': 'Tripel',
     'alcohol': 8.5,
     'price': 280,
     'quantity': 330,
     'imageUrl': 'assets/Beers/leffe-triple.png'
     },
    {'brand': 'Miller',
     'beer': 'Ace strong',
     'alcohol': 7.5,
     'price': 170,
     'quantity': 650,
     'imageUrl': 'assets/Beers/miller-ace.png'
     },
    {'brand': 'Miller',
     'beer': 'High Life',
     'alcohol': 4.6,
     'price': 160,
     'quantity': 650,
     'imageUrl': 'assets/Beers/miller-high_life.png'
     },
    {'brand': 'Royal Challange',
     'beer': 'Premium',
     'alcohol': 5.0,
     'price': 135,
     'quantity': 650,
     'imageUrl': 'assets/Beers/royal_challenge-premium.png'
     },
    {'brand': 'Sandpiper',
     'beer': 'Premium',
     'alcohol': 4.6,
     'price': 170,
     'quantity': 500,
     'imageUrl': 'assets/Beers/sandpiper-premium.png'
     },
    {'brand': 'Simba',
     'beer': 'Stout',
     'alcohol': 4.5,
     'price': 130,
     'quantity': 750,
     'imageUrl': 'assets/Beers/simba-stout.png'
     },
    {'brand': 'Tuborg',
     'beer': 'Green',
     'alcohol': 4.6,
     'price': 155,
     'quantity': 650,
     'imageUrl': 'assets/Beers/tuborg-green.png'
     },
    {'brand': 'Tuborg',
     'beer': 'Premium Mild',
     'alcohol': 7.5,
     'price': 130,
     'quantity': 650,
     'imageUrl': 'assets/Beers/tuborg-premium_mild.png'
     },
    {'brand': 'White owl',
     'beer': 'Diablo',
     'alcohol': 5.5,
     'price': 280,
     'quantity': 650,
     'imageUrl': 'assets/Beers/white_owl-diablo.png'
     },
    {'brand': 'White owl',
     'beer': 'Spark',
     'alcohol': 5.0,
     'price': 240,
     'quantity': 650,
     'imageUrl': 'assets/Beers/white_owl-spark.png'
     },
    {'brand': 'Zingaro',
     'beer': 'Super strong',
     'alcohol': 7.5,
     'price': 100,
     'quantity': 650,
     'imageUrl': 'assets/Beers/zingaro-strong.png'
     }
]
